### ISSUE TITLE
Error setting up codeAction handler

### ISSUE THREAD

**Issue by hood** [RishabhRD/lspactions#2]
Getting 
```
Error detected while processing /home/username/.config/nvim/init.vim:
line 42069:
E5108: Error executing lua .../lspactions/lua/lspactions/codeaction.lua:1: attempt to index field 'keymap' (a nil value) 
```
With the following configuration
```
vim.lsp.handlers["textDocument/codeAction"] = require'lspactions'.codeaction
vim.cmd [[ nnoremap <leader>ga :lua require'lspactions'.code_action()<CR> ]]
```

**Comment by RishabhRD** [comment]
``Plug 'tjdevries/astronauta.nvim'`` is a dependency. I know..... But it would be merged in neovim in sometime... so I just used it.

**Comment by hood** [comment]
I already have it installed. I'm still getting the error.

**Comment by RishabhRD** [comment]
![keymap](https://user-images.githubusercontent.com/26287448/135680965-90c0087f-fdc1-428e-a819-160ba88a8b58.png)

In neovim config ``runtime plugin/astronauta.vim`` is necessary to be there to load vim.keymap first so that lspactions can use it. (This is how people are using it currently.... I hope it would get merged to master soon)

**Comment by hood** [comment]
Now I'm getting
```
E5108: Error executing lua ...ig/nvim/plugged/lspactions/lua/lspactions/codeaction.lua:102: bad argument #1 to 'pairs' (table expected, got nil)
```

**Comment by hood** [comment]
Now the issue is hitting `Enter` to select an action has no effect.

**Comment by RishabhRD** [comment]
The issue is fixed now....

**Comment by chriztheanvill** [comment]
> ![keymap](https://user-images.githubusercontent.com/26287448/135680965-90c0087f-fdc1-428e-a819-160ba88a8b58.png)
> 
> In neovim config `runtime plugin/astronauta.vim` is necessary to be there to load vim.keymap first so that lspactions can use it. (This is how people are using it currently.... I hope it would get merged to master soon)

I had this same issue, with ``` vim.cmd [[ runtime plugin/astronauta.vim ]] ``` its fixed.
