### ISSUE TITLE
[Feature-Request] Could you provide an action to show the line diagnostics?

### ISSUE THREAD

**Issue by nyngwang** [RishabhRD/lspactions#4]
As title.

**Comment by RishabhRD** [comment]
Yep. I have plans for that... I would try to do this in this weekend

**Comment by nyngwang** [comment]
This is a extremely great plugin!

**Comment by RishabhRD** [comment]
Thanks man. I would love to experiment with more lsp capabilities.

**Comment by RishabhRD** [comment]
Neovim currently has a good API for diagnostics. There are many deprecated functions vim.lsp namespace that is most possibly be removed in future. I am adding those as initial implementation. Borders and things can be customized and can be a part of PR later. lspactions.diagnostic namespace now ports some of deprecated function in vim.lsp namespace.

Those implementations may not be the best implementation but we can use them as initial implementation and try to improve as more requirements arrive.

**Comment by nyngwang** [comment]
Could you also update the README.md on its usage? I think it will be very helpful for newbies.
And! If you know and could implement this function: shown on hover it will be extremely helpful for me(I don't know how to implement it).

Thank you!

**Comment by RishabhRD** [comment]
Sure!😅 I just forgot about readme bcz I was little busy in my academics. I would update that in some hours. Thanks for fruitful suggestions. This is a great contribution😃
